{% set name = "pickle-compat" %}
{% set version = "2.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pickle-compat-{{ version }}.tar.gz
  sha256: 5325149ef9b4c1eab53f5e5f8883e4115e279c268cf0fca06e9c85c52b16e86d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - poetry >=1.0.5
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - pickle_compat
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/Doist/pickle-compat
  summary: Python 2/3 compatibility layer for Pickle
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ickc
